# Generated by Django 6.0 on 2026-01-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='missions', to='skills.skill'),
        ),
    ]
