# Generated by Django 5.2.9 on 2026-01-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_userskill_certificate_alter_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
