# Generated by Django 6.0 on 2026-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('preselected', 'Présélectionné'), ('confirmed', 'Confirmé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('hours_validated', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
